name: remotescreens
version: '0.1'
summary: Remote Screens by Oele Geirnaert
description: |
 remote screen service
base: core18
# grade: stable
grade: devel
# confinement: strict
confinement: devmode
icon: remote_screens.png

architectures:
  - build-on: amd64
  - build-on: arm64
    # run-on: [amd64, arm64]

apps:
  start:
    command: bin/start # from setup.py entry_points
    plugs: [home,network-bind]
    daemon: simple
    restart-condition: always

  help:
    command: bin/help # from setup.py entry_points
    plugs: [home,network-bind]

  register:
    command: bin/register # from setup.py entry_points
    plugs: [home,network-bind]

parts:
  server:
    # plugin: nil
    plugin: python
    python-version: python3
    python-packages: [websocket_client, requests, psutil, Xlib]
    source: .
    # stage-packages: [ncbi-blast+]
    # override-build: |
    #     snapcraftctl build
    #     cp $SNAPCRAFT_PART_SRC/src/app.py $SNAPCRAFT_PART_INSTALL/usr/bin/
    #     chmod +x $SNAPCRAFT_PART_INSTALL/usr/bin/scr/app.py
